### ISSUE TITLE
index.ejs reporta erro de sintaxe 

### ISSUE THREAD

**Issue by williambsb** [luiztools/livro-node#1]
Unexpected token ')' in /Volumes/MacHD/Will/Code/Node.js/Crud/views/index.ejs

Peguei o mesmo código do repositório porem a linha 39 reclama de um ) 

E sem o ) falha também ...

**Comment by luiztools** [comment]
Boa noite William. Qual bloco de código do livro você está se referindo? Todos eles possuem uma numeração logo acima do bloco.

**Comment by williambsb** [comment]
Ola @luiztools era no Bloco CRUD ... mas verifiquei um %> a mais antes do else ... deve ter sido no meu copy & paste e algo ficou errado. Ja estou fechando .
